### ISSUE TITLE
Usage aiida-testing package

### ISSUE THREAD

**Issue by danielhollas** [aiida-icon/aiida-icon#18]
Hi! :wave: 

I came across this package while looking into who is using the `aiida-testing` package (currently published on pypi as `aiida-testing-dev`). You have a dependency on this package in `pyproject.toml` but it's doesn't look like there are any tests that use fixtures from this package. Are you planning to utilize it in the future?

(for context: I will be working on `aiida-testing` package as part of AiiDA coding week this week so it would be great to know about your use case, if any!)

**Comment by DropD** [comment]
Oh, thanks for letting me know. It's true, I am not currently using aiida-testing and the requirement is there (erroneously) because I was trying to set it up.

I was hoping to set up something like my parsing tests with an easy route forward for when I can run the actual jobs in CI, so I can test the parsing against actual runs in CI, but against stored outcomes locally. Ideally without having to write a whole shell script that copies around the pretend output files.

I'm interested to hear in which direction you are planning to take the package. Let me know if I can help with a more detailed use case description or anything else.

**Comment by danielhollas** [comment]
@DropD Thank you for a quick reply! :heart_hands:  Would love to make something that works for you (but note that I am still learning about `aiida-testing` package myself so I don't know how far I'll get).

I've outlined my plan in https://github.com/aiidateam/aiida-testing/issues/74, if you have any more thoughts please comment there. Also LMK in case you are interested in reviewing any of the PRs.

**Comment by DropD** [comment]
Great, let's take the discussion there! Thanks again for reaching out.
